spring:
  application:
    name: msa-museum-server
  datasource:
    url: jdbc:postgresql://localhost:5432/msa_museum
    username: xianxian
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

file:
  storageLocation: public/files
  userAvatarLocation: public/userAvatars
  artifactAvatarLocation: public/artifactAvatars

  storageUrlBase: /files/
  userAvatarUrlBase: /userAvatars/
  artifactAvatarUrlBase: /artifactAvatars/