spring:
  application:
    name: msa-museum-server
  datasource:
    url: jdbc:postgresql://localhost:5432/msa_museum
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
file:
  storage:
    disk: d://
    location: msa-museum/files/