spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: msa-museum-server
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
file:
  storageLocation: ${FILE_STORAGE_LOCATION}
  userAvatarLocation: ${FILE_USER_AVATAR_LOCATION}
  artifactAvatarLocation: ${FILE_ARTIFACT_AVATAR_LOCATION}
  storageUrlBase: ${FILE_STORAGE_URL_BASE}
  userAvatarUrlBase: ${FILE_USER_AVATAR_URL_BASE}
  artifactAvatarUrlBase: ${FILE_ARTIFACT_AVATAR_URL_BASE}
