spring:
  datasource:
    url: jdbc:postgresql://49.51.202.173:5432/msa_museum
    username: postgres
    password: 20071028zhanG!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
file:
  storageLocation: C://upload/files
  userAvatarLocation: C://upload/userAvatars
  artifactAvatarLocation: C://upload/artifactAvatars


